### ISSUE TITLE
datastore: loading nested structs is broken

### ISSUE THREAD

**Issue by aqua** [GoogleCloudPlatform/gcloud-golang#247]
In constructing the codec for loading struct properties from datastore, datastore.getStructCodecLocked() populates a map structCodec.byName with the names of the fields from that struct.  When one of those fields is another struct, it instead recurses into itself and populates .byName with names of the form OuterFieldName.InnerFieldName (it does not insert the name of the inner struct field).  All that seems fine, except that when the codec is actually called by propertyLoader.loadOneElement(), it expects to find an entry whose name corresponds to the properties returned by datastore -- which will, in the case of the struct field, be the name of the struct field itself, that was never populated.  This causes client.GetAll() and iterator.Next() to fail with "no such struct field: OuterFieldName" errors -- extra misleading, because the outer field name actually did exist.

I've noticed this with code approximately like the following; the entities, which were originally populated in datastore via the Go appengine SDK's datastore package, have a definition along these lines:

```
type StoredEntity struct {
  UnrelatedField string
  Location appengine.Location
}
```

The struct codec's byName field gets populated with appengine.Location's own fields, hence Location.Lng and Location.Lat, but not Location, and the fetch fails (if Location is changed in the client code to some other type, like int, the load succeeds, albeit with a zero value for Location).

**Comment by aqua** [comment]
Experimenting some more I think I see the surrounding context -- this problem is triggered by reading entities containing nested structs (or at least the appengine.GeoPoint struct, which is a recognized property in the AE datastore) that were written via the Go appengine SDK.  In the StoredEntity example above, the Location field will be named 'Location' as written via the SDK and viewed through the production entity viewer, and cannot be read via gcloud-golang.  If it were written by gcloud-golang, it would be stored separately as Location.Lat and Location.Lng properties and can be read by gcloud-golang, but not by code compiled against the SDK.

This is going to make migrating live services between the two APIs a challenge.

**Comment by okdave** [comment]
See #46 – support for the geo point will be coming very shortly, and should fix this issue for you.

**Comment by cnbuff410** [comment]
Can we get a notification when it's supported? Just doesn't want to miss it out since it's not mentioned on the readme page.

**Comment by cnbuff410** [comment]
Any update here?

**Comment by okdave** [comment]
The blocking issue #46 has been fixed now, so this should be resolved.

**Comment by cnbuff410** [comment]
Is this already released or not yet? I just did a local test and seems like still not working on my side.

**Comment by okdave** [comment]
@cnbuff410 it is released, did you follow through and read the attached issue?
I don't really know what your local test was trying to do, so I'm not really sure in why it might be failing.

**Comment by cnbuff410** [comment]
My local test is just to load a dataset from datastore with GeoPoint in the struct. I get exactly same error as this issue:

https://github.com/GoogleCloudPlatform/gcloud-golang/issues/187

**Comment by okdave** [comment]
The following test case works as expected:

```go
func TestGeoPoint(t *testing.T) {
	if testing.Short() {
		t.Skip("Integration tests skipped in short mode")
	}
	ctx := context.Background()
	client := newClient(ctx, t)
	defer client.Close()

	type Outer struct {
		A int
		B GeoPoint
	}
	outer := &Outer{
		A: 12,
		B: GeoPoint{12.5, 25.0},
	}

	key := NewKey(ctx, "GeoPoint", "GeoPoint"+suffix, 0, nil)
	if _, err := client.Put(ctx, key, outer); err != nil {
		t.Fatalf("client.Put: %v", err)
	}
	defer func() {
		if err := client.Delete(ctx, key); err != nil {
			t.Fatalf("client.Delete: %v", err)
		}
	}()

	var got Outer
	if err := client.Get(ctx, key, &got); err != nil {
		t.Fatalf("client.Get: %v", err)
	}
	if !reflect.DeepEqual(got, *outer) {
		t.Errorf("Geopoint didn't survive the trip.\ngot:  %v\nwant: %v", got, outer)
	}
}
```

You'll need to be more specific about what you're doing. Note that you need to use the `GeoPoint` provided by this datastore package, and not `appengine.GeoPoint`.

**Comment by cnbuff410** [comment]
You are right, the GeoPoint from different package was the issue. Thanks a lot!
